meta_product_name: "Walkerz"
meta_title: "Walkerz - visites guidées gratuites"
meta_description: "Une plateforme collaborative qui vous permet de suivre des visites guidées gratuites et personnalisées"
meta_image: "cover.png" # should exist in `app/assets/images/`
